App\Entity\AdminRole:
    type: entity
    table: admin_role
    indexes:
        admin_id:
            columns:
                - admin_id
                - role_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        adminId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: admin_id
        roleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: role_id
    lifecycleCallbacks: {  }
