App\Entity\Category:
    type: entity
    table: category
    indexes:
        lang_id:
            columns:
                - lang_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mnTitle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: mn_title
        enTitle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: en_title
        slug:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        sortnum:
            type: integer
            nullable: false
            options:
                unsigned: false
        isPremium:
            type: boolean
            nullable: false
            column: is_premium
    manyToOne:
        lang:
            targetEntity: Lang
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lang_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
