App\Entity\Contact:
    type: entity
    table: contact
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        body:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        created:
            type: datetime
            nullable: false
        readed:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
