App\Entity\Grade:
    type: entity
    table: grade
    indexes:
        teacher_id:
            columns:
                - teacher_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        created:
            type: datetime
            nullable: false
    manyToOne:
        teacher:
            targetEntity: Teacher
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                teacher_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
