App\Entity\MyKeybroard:
    type: entity
    table: my_keybroard
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 'Дахин давтагдашгүй дугаар'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Гарын хавтаны төрлийн нэрүүд'
        items:
            type: text
            nullable: false
            length: 0
            options:
                fixed: false
                comment: 'json data байна. энэ нь аль товчийг дарахийг тодоруулана'
    lifecycleCallbacks: {  }
