App\Entity\PasswordReset:
    type: entity
    table: password_reset
    indexes:
        student_id:
            columns:
                - student_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        activationkey:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'Нууц үг сэргээх нууц код байна.'
            column: activationKey
        createdAt:
            type: datetime
            nullable: false
            options:
                comment: 'Үүсгэсэн огноо'
            column: created_at
    manyToOne:
        student:
            targetEntity: Student
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
