App\Entity\Role:
    type: entity
    table: role
    uniqueConstraints:
        role:
            columns:
                - role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
    lifecycleCallbacks: {  }
