App\Entity\UpgradedUsers:
    type: entity
    table: upgraded_users
    indexes:
        student_id:
            columns:
                - student_id
        upgrade_id:
            columns:
                - upgrade_id
                - student_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        upgradeId:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: upgrade_id
        studentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: student_id
        tranDate:
            type: date
            nullable: false
            column: tran_date
        expDate:
            type: date
            nullable: false
            column: exp_date
        ipAddress:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: ip_address
        isPaid:
            type: boolean
            nullable: false
            column: is_paid
        invoiceNumber:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
                comment: 'invoice number is here.'
            column: invoice_number
        isSend:
            type: boolean
            nullable: false
            options:
                comment: 'Мэйл илгээсэнг тэмдэглэнэ.'
            column: is_send
    lifecycleCallbacks: {  }
